INSERT INTO person_company (
    personId,
    compId,
    personName,
    relationShip,
    compName,
    preCompName,
    unifiedCode,
    regNo,
    logoWord,
    region,
    regAddr,
    startDate,
    regCap,
    openStatus,
    telephone,
    mailbox,
    bankInfo,
    level
 ) VALUES (
    :personId,
    :compId,
    :personName,
    :relationShip,
    :compName,
    :preCompName,
    :unifiedCode,
    :regNo,
    :logoWord,
    :region,
    :regAddr,
    :startDate,
    :regCap,
    :openStatus,
    :telephone,
    :bankInfo,
    :mailbox,
    :level
 ) ON DUPLICATE KEY UPDATE
 relationShip = CASE WHEN INSTR(relationShip,:relationShip) > 0 THEN relationShip ELSE CONCAT(relationShip,:relationShip) END
